### ISSUE TITLE
[Epic] Additional information for entities

### ISSUE THREAD

**Issue by SebieF** [biocentral/biocentral#1]
**User Story**
As a researcher, I want to have more information available about my data (e.g. proteins) so that I do not have to switch to other sources and can find important information quickly.

**Additional context**
The following information would be useful:

* Taxonomy
* GO Annotation (Protein)
* Subcellular location

**Acceptance criteria**

- [ ] Information can be retrieved
- [ ] Information can be displayed
- [ ] Information can be used for data analysis and model training

**Comment by SebieF** [comment]
A possibility would be to use [gget](https://github.com/pachterlab/gget), especially for genome data. Or a direct connection to Uniprot or PDB.

**Comment by SebieF** [comment]
Another option would be to use bioservices https://github.com/cokelaer/bioservices

**Comment by SebieF** [comment]
TED Domains: https://github.com/UCLOrengoGroup/ted-web
Are also part of the AlphaFoldDB, could be possible to search sequences via AlphaFoldDB in Ted.
