### ISSUE TITLE
[Epic] Make results from biocentral reproducable

### ISSUE THREAD

**Issue by SebieF** [biocentral/biocentral#11]
**User Story**
As a researcher, I want to be always able to reproduce my findings in biocentral so that I can follow open science best practices. 

**Additional context**

**Acceptance criteria**

- [ ] Error logging and storing to file (#7)
- [ ] Automatic saving of all databases on changes (#8)
- [ ] Automatic saving of error and command logs (#9)
- [ ] Executable command log (#10)
