### ISSUE TITLE
[Epic] Improve embedding visualization

### ISSUE THREAD

**Issue by SebieF** [biocentral/biocentral#30]
**User Story**
As a researcher working with embeddings, I want to use proven and state-of-the-art methods to analyze my embeddings so that I can make informed decisions about my data and model training.

**Additional context**

Interesting related project: https://github.com/tsenoner/ProtSpace

**Acceptance criteria**

- [ ] Improve UMAP display (#29)
- [ ] Test other reduction methods for per-sequence embeddings and visualize the distributions (#26)
- [ ] Add new embedding visualizations (e.g. t-SNE/3D/...)
