### ISSUE TITLE
[Epic] Add support for protein structure data and analysis

### ISSUE THREAD

**Issue by SebieF** [biocentral/biocentral#32]
**User Story**
As a researcher working with protein data, I want to be able to work with protein structure data in biocentral so that I can use it for my research.

**Acceptance criteria**

- [ ] Support for pdb files (https://github.com/biocentral/bio_flutter/issues/4)
- [ ] Support for foldseek (https://github.com/biocentral/bio_flutter/issues/4)
- [ ] Support for ProstT5 embeddings
