### ISSUE TITLE
[Epic] Create protein comparison plugin

### ISSUE THREAD

**Issue by SebieF** [biocentral/biocentral#34]
**User Story**
As a researcher working with protein data, I want to be able to compare my database of proteins with another set of proteins so that I can find relations between the two datasets.

**Acceptance criteria**

The following comparison scores must be implemented:
- [x] Levensthein-distance 
- [ ] foldseek (#33)
- [ ] embeddings: cosine distance, euclidean distance (both for structure and sequence embeddings)

A new plugin should be created, that can do the following:
- [ ] Create a dialog, where the different comparison methods can be selected and weighted
- [ ] Perform the calculation
- [ ] Display the results
- [ ] Save the results to disk
