### ISSUE TITLE
[Epic] Create cell data plugin

### ISSUE THREAD

**Issue by SebieF** [biocentral/biocentral#40]
**User Story**
As a biologist working with cell data, I want to be able to load my data into biocentral so that I can analyze it and train models for it.

**Acceptance criteria**

Develop a new core plugin "Cell Data"
- [ ] Created cell data model
- [ ] Load cell data
- [ ] Save cell data
- [ ] Adapt ColumnWizards if necessary
- [ ] View vector/numerical information in embeddings plugin
- [ ] Training and inference of a model on cell data is possible
- [ ] Added unit tests for data handling
